//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Operation.cs
//  @ Date : 2017. 06. 21.
//  @ Author : 
//
//


namespace CalculateDerivative.Operations
{
    public sealed class Constant : Node
    {
        protected override int ArgumentNumber => 0;
        public double Value { get; }
        public Constant(double value) : base(null)
        {
            Value = value;
        }
        public override bool Equals(object obj)
        {

            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }

            return Value.Equals(((Constant)obj).Value);
        }
        public override int GetHashCode()
        {
            var hash = 17;
            hash = hash * 23 + ArgumentNumber.GetHashCode();
            hash = hash * 23 + Children.GetHashCode();
            hash = hash * 23 + Value.GetHashCode();
            return hash;
        }

        public override MathExpression Derivative(string variable) => new MathExpression(new Constant(0));
    }
}
