//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Operation.cs
//  @ Date : 2017. 06. 21.
//  @ Author : 
//
//


namespace CalculateDerivative.Operations
{
    public sealed class Divide : Node
    {
        protected override int ArgumentNumber => 2;
        public Divide(Node[] children):base(children)
        {
        }

        public override MathExpression Derivative(string variable)
        {
            var derivatives = Derivatives(variable);
            return new MathExpression(new Divide(new Node[]
            {
                new Subtract(new Node[]
                {
                    new Multiply(new[] {Children[1], derivatives[0]}), new Multiply(new[] {Children[0], derivatives[1]})
                }),
                new Power(new[] {Children[1], new Constant(2)})
            }));
        }
    }
}
