//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : MathExpression.cs
//  @ Date : 2017. 06. 21.
//  @ Author : 
//
//


namespace CalculateDerivative
{
    public class MathExpression
    {
        public Node Root{ get; }

        public MathExpression(Node root)
        {
            Root = root;
        }
        public override bool Equals(object obj)
        {

            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }

            return Root.Equals(((MathExpression)obj).Root);
        }
        public override int GetHashCode()
        {
            var hash = 17;
            hash = hash * 23 + Root.GetHashCode();
            return hash;
        }
    }
}
